apiVersion: v1
kind: Service
metadata:
  name: rm-backend
  namespace: rm-annual-summary-uat
  labels:
    app.kubernetes.io/name: rm-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rm-backend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rm-backend
  namespace: rm-annual-summary-uat
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rm-backend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rm-backend
  namespace: rm-annual-summary-uat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rm-backend
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
