-- H2 schema mirroring the columns needed by MyBatis mapper tests.
-- The base table rm_perf_summary_snapshot has all columns the production
-- view exposes; the view is approximated by an H2 view that picks the row
-- with the latest biz_date per (employee_id, period_type).

CREATE TABLE rm_perf_summary_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_date DATE NOT NULL,
    employee_id VARCHAR(64) NOT NULL,
    period_type VARCHAR(16) NOT NULL,
    new_merchants BIGINT NOT NULL DEFAULT 0,
    qualified_merchants BIGINT NOT NULL DEFAULT 0,
    active_merchants BIGINT NOT NULL DEFAULT 0,
    income_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
    batch_finished_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_delayed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_snap UNIQUE (biz_date, employee_id, period_type)
);

CREATE VIEW rm_latest_perf_summary_snapshot AS
SELECT s.employee_id,
       s.period_type,
       s.biz_date,
       s.new_merchants,
       s.qualified_merchants,
       s.active_merchants,
       s.income_amount,
       s.batch_finished_at,
       s.is_delayed
FROM rm_perf_summary_snapshot s
WHERE (s.employee_id, s.period_type, s.biz_date) IN (
    SELECT employee_id, period_type, MAX(biz_date)
    FROM rm_perf_summary_snapshot
    GROUP BY employee_id, period_type
);

CREATE TABLE rm_aum_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_date DATE NOT NULL,
    employee_id VARCHAR(64) NOT NULL,
    aum_total DECIMAL(18, 2),
    CONSTRAINT uq_aum UNIQUE (biz_date, employee_id)
);
